---
title: FLC Monitoring
author: Sea State
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    fig_caption: true
fontsize: 10pt
geometry: margin=0.75in
fig.env: graphicx
---

```{r global_options, include=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(fig.width=7.0, fig.height=2.0, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
library(pander)
library(scales)
```

```{R,runFLCscript}
	#source("FLC_report1.R")
	source("FLC_FleetReport.R")
```



### Overview
```{R,HalibutDMR}
	h1 <- OverviewTable[1,1]
	h2 <- OverviewTable[1,2]

	delta <- (h2-h1)/h1
```

The total cumulative catch of Pacific cod at the end of `r Period$eow` was `r prettyNum(round(OverviewTable[2,2]),big.mark=",")` mt.  At the same week in the previous year, the cumulative catch was `r prettyNum(round(OverviewTable[2,1]),big.mark=",")` mt (Table 1). Halibut encounters to date has `r ifelse(delta < 0,"decreased","increased")` by `r percent(abs(delta))` over last year.  The cumulative halibut mortality to date for 2016 is `r prettyNum(round(OverviewTable[5,2]),big.mark=",")` mt, and at the same time last year `r prettyNum(round(OverviewTable[5,1]),big.mark=",")` mt.


```{R,OverviewTable}
	library(pander)
  panderOptions('digits', 2)
  panderOptions('round', 2)
  panderOptions('keep.trailing.zeros', TRUE)
  panderOptions('big.mark', ",")
  panderOptions('keep.line.breaks', TRUE)
  pander(x=OverviewTable, 
  	caption=paste0("Catch statistics (in metric tons) for week ending ",Period$eow," (Week ", .WEEK, ")."),justify='right')
```


```{R,codCatch,fig.margin = FALSE,fig.cap="Weekly catch of Pacific cod, and encounters (mt) of Pacific Halibut."}
	G2 + theme_bw(base_size=10)
```



### NMFS Stat Area Summary
```{R,catchSummary}
	library(pander)
  panderOptions('digits', 0)
  panderOptions('round', 2)
  panderOptions('table.style','multiline')
  panderOptions('keep.trailing.zeros', TRUE)
  panderOptions('big.mark', ",")
  #pander(x=statAreaRates, keep.line.breaks = TRUE, caption=paste0("Halibut encounter rates for the week ending ",Period$eow,"."),justify='right')
  pander(x=sar_Table, keep.line.breaks = TRUE, caption=paste0("Halibut encounter rates for the week ending ",Period$eow,"."),justify='right')
```



### Vessel Rates and Ranking
```{R,vesselRates}
	pander(vesselRates,
					keep.line.breaks = TRUE,
					justify=c('center','left','center','center'),
					caption=paste0("Vessel rates in kg of halibut per ton of groundfish for the week ending ",Period$eow, "."),
					split.cells=c(10,290,15,15))
```




### Viability Sampling
Total number of hauls sampled to date is 
`r prettyNum(NumberOfHaulsSampled[2,2],big.mark=",")`, and the total number of hauls sampled in `r NumberOfHaulsSampled[1,1]` was `r prettyNum(NumberOfHaulsSampled[1,2],big.mark=",")`.

```{R,ViabilitySummary}
	library(pander)
  panderOptions('digits', 2)
  panderOptions('round', 2)
  panderOptions('keep.trailing.zeros', TRUE)
	
	today = .TODAY-1
	set.caption(paste("Viability samples as of",today), permanent = FALSE)
	pander(TBL_1)
```



### Discard Mortality Rates (DMR)

The `r year(.TODAY)` discard mortality rate based on all viability samples (Table 4) to date is `r dmr[1,2]` for trips targeting `r dmr[1,1]` (Table 5), and `r dmr[2,2]` for trips targeting `r dmr[2,1]`.

```{R,DMR_Table}
	library(pander)
	pander(dmr,
				 	keep.line.breaks = TRUE,
				 	caption="Halibut discard mortality rates based on viability sampling.")
```

### Blue King Crab 
<!-- I have a bug in here -->
```{R, BKCcalculations}
	url2015 <- "https://alaskafisheries.noaa.gov/sites/default/files/reports/car250_psc_crab2015.csv"

	car250_psc_crab2015 <- read.csv(url2015,skip=8)
	
	url2016 <- "https://alaskafisheries.noaa.gov/sites/default/files/reports/car250_psc_crab2016.csv"
	car250_psc_crab2016 <- read.csv(url2016,skip=9)
	# rename(AREA=REPORTING.AREA)

	bkc <- full_join(car250_psc_crab2015,car250_psc_crab2016) %>%
				 # mutate(Area=ifelse(is.na(REPORTING.AREA),AREA,REPORTING.AREA)) %>%
				 rename(AREA=REPORTING.AREA) %>%
				 filter(SPECIES=="BKCR",GEAR=="HAL",
				 SECTOR %in% c("CP","Catcher Processor")) %>%
				 mutate(WEEK = mdy(WEEK)) %>%
				 mutate(WeekNumber=week(WEEK)) %>%
				 mutate(Year=year((WEEK))) %>%
				 tbl_df()


	bkc1 <- bkc %>% group_by(Year) %>% summarise("Blue King Crab"=sum(NUMBER.OF.CRAB))

	bkc2 <- bkc %>% filter(WeekNumber %in% .WEEK, Year %in% .YEAR) %>% group_by(Year,AREA) %>% summarise(NumberOfCrab=sum(NUMBER.OF.CRAB))  %>% spread(Year,NumberOfCrab)

	colnames(bkc2) <- c("Area",paste0("Week ",.WEEK," (",.YEAR,")"))

	fdf <- car250_psc_crab2016 

	crab2016 <- car250_psc_crab2016 %>% 
		filter(SPECIES.NAME == "Blue King Crab",NUMBER.OF.CRAB > 0,GEAR=="HAL",SECTOR == "Catcher Processor",TARGET=="Pacific Cod") %>% 
		tbl_df() %>% 
		summarise(No.of.Crab=sum(NUMBER.OF.CRAB))
```

```{R,BlueKingCrab}
	source("FLC_bkc.R")
	iyr <- year(.TODAY)
	idx <- which(AnnualCatch[,1]==iyr)
```




Total number of blue king crab caught in hook & line gear to date in `r year(.TODAY)` is `r prettyNum(crab2016,big.mark=",")  `. In `r year(.TODAY)-1` the total number of blue king crab was `r prettyNum(bkc1[1,2],big.mark=",")`.

```{R,BlueCrabTable}
	pander(bkc2,keep.line.breaks = TRUE,
				 	caption=paste0("Number of Blue King Crab caught in Reporting Area in  week ", .WEEK, ". No activity is denoted with NA."))
```


### Sea Birds
**NOTE: Work in progress.  I'm still trying to validate these numbers with the regional office. Stay tuned.  
```{R,Birds}
	source("FLC_SeaBirds.R")
	pander(tbl.2)
```




<!-- 
### Catch-to-date by gear type.
Show a table with the breakdown of BSAI groundfish catch & bycatch by gear types: HAL, NPT, POT, PTR, ALL.



### Halibut hotspots
Heat map based on the halibut encounter rates in the H\&L CP fishery.

How this will eventually work, I'm just calculating the nearest neighbor density for all sets in the past week where the halibut encounter rate is greather than the median rate of all sets for that week.  For now the rate is based on (kg Halibut pre mortality)/(Official Total Catch)

```{R,fig.width=4,fig.height=4}
	#bmap
```

 -->